# Generated by Django 4.0.5 on 2022-07-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='authentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('confirmed', models.SmallIntegerField(null=True)),
                ('number', models.IntegerField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('key', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chunkedfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=20, null=True)),
                ('filesize', models.IntegerField(null=True)),
                ('filetype', models.CharField(max_length=100, null=True)),
                ('owner_id', models.IntegerField(null=True)),
                ('date_chunked', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='name',
        ),
        migrations.AddField(
            model_name='accounts',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='firstname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='is_active',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='lastname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
