# Generated by Django 4.0.5 on 2022-07-30 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_accounts_chunkit_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authentication',
            name='user_id',
        ),
    ]
