# Generated by Django 4.0.5 on 2022-07-30 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_authentication_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentication',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.chunkit_users'),
        ),
    ]
