# Generated by Django 4.0.5 on 2022-07-30 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_authentication_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunkedfile',
            name='owner_id',
        ),
    ]
