# Generated by Django 4.0.5 on 2022-07-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_chunkedfile_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkedfile',
            name='owner_id',
            field=models.ManyToManyField(null=True, to='accounts.chunkit_users'),
        ),
    ]
